### ISSUE TITLE
Required "app_id" key (FACEBOOK_APP_ID) 

### ISSUE THREAD

**Issue by KalimeroMK** [laravel-notification-channels/facebook-poster#47] opened 2020-07-11 23:04 UTC
Hi,

I've followed every step but I can't fix this problem.
Required "app_id" key not supplied in the config and could not find fallback environment variable "FACEBOOK_APP_ID"

My .env

FACEBOOK_APP_ID=my_app_id
FACEBOOK_APP_SECRET=my_app_secret
FACEBOOK_ACCESS_TOKEN=my_access_token
My config/services.php

'facebook_poster' => [
   'app_id' => env('FACEBOOK_APP_ID'),
   'app_secret' => env('FACEBOOK_APP_SECRET'),
   'access_token' => env('FACEBOOK_ACCESS_TOKEN'),
],

The same problem on my end and on a dd(config('services.facebook_poster')) return 
```
^ array:3 [▼
  "app_id" => "447881111111111"
  "app_secret" => "447886111111111|JOf-XpjhoVj6PoX8iFkY_1ym2bY"
  "access_token" => "EAAGXWaqI5dgBADFVPVPcXH60sNruOPyG6xPefTcOpBjTt3GlSUj8eM27pClYgrZCJunhWF4FwIfodiBJHsB5ywyApric2gcH4mPlBh4tygcYOd8oGH5wJ8ZAKKktK61UDXS2H8ZBO5eduKv2ijCko3hXffKPh0Z ▶"
]

but on dd($config) in vendor/facebook/graph-sdk/src/Facebook/Facebook.php return 

^ array:9 [▼
  "app_id" => null
  "app_secret" => null
  "default_graph_version" => "v2.10"
  "enable_beta_mode" => false
  "http_client_handler" => null
  "persistent_data_handler" => null
  "pseudo_random_string_generator" => null
  "url_detection_handler" => null
  "default_access_token" => "EAAGXWaqI5dgBADFVPVPcXH60sNruOPyG6xPefTcOpBjTt3GlSUj8eM27pClYgrZCJunhWF4FwIfodiBJHsB5ywyApric2gcH4mPlBh4tygcYOd8oGH5wJ8ZAKKktK61UDXS2H8ZBO5eduKv2ijCko3hXffKPh0Z ▶"
]
```

**Comment by dwightwatson** [comment] 2020-07-13 05:07
This is just a duplicate of #44?

**Closed as completed by dwightwatson** 2020-07-13 05:07 UTC
